name: Publish On NuGet

on:
  push:
    tags: "*"

jobs:
  publish:
    name: List on NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Package Id
        run: bash scripts/package-name-update.sh ${{secrets.NUGET_PACKAGE_NAME}}
        
      - name: Build
        run: dotnet build --configuration Release "src/OpenVASP.CSharpClient.sln"

      - name: Create the package
        run: dotnet pack --configuration Release src/OpenVASP.CSharpClient/OpenVASP.CSharpClient.csproj /p:Version=${GITHUB_REF#refs/tags/}
      - name: Publish the package to GPR
        run: dotnet nuget push src/OpenVASP.CSharpClient/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_API_KEY }}
